# Generated by Django 6.0.7 on 2026-07-29 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('acronym', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('acronym', models.CharField(max_length=30)),
                ('plan_type', models.CharField(choices=[('PEI', 'PEI'), ('PESP', 'PESP'), ('PPA', 'PPA'), ('OUTRO', 'Outro')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('NAO_INICIADA', 'Não iniciada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('ATRASADA', 'Atrasada'), ('BLOQUEADA', 'Bloqueada'), ('SUSPENSA', 'Suspensa')], default='NAO_INICIADA', max_length=15)),
                ('expected_delivery', models.CharField(blank=True, max_length=255)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.actionplan')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('acronym', models.CharField(blank=True, max_length=30)),
                ('unit_type', models.CharField(choices=[('ORGAO', 'Órgão'), ('UNIDADE', 'Unidade'), ('SETOR', 'Setor')], max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organizationalunit')),
            ],
        ),
        migrations.CreateModel(
            name='PlanArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('DIMENSAO', 'Dimensão BSC'), ('EIXO', 'Eixo Estratégico'), ('OBJETIVO', 'Objetivo Estratégico'), ('PROJETO', 'Projeto Estratégico')], max_length=12)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.planartifact')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.plan')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('NAO_INICIADA', 'Não iniciada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('ATRASADA', 'Atrasada'), ('BLOQUEADA', 'Bloqueada'), ('SUSPENSA', 'Suspensa')], default='NAO_INICIADA', max_length=15)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.planartifact')),
                ('coordinating_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizationalunit')),
                ('participating_units', models.ManyToManyField(blank=True, related_name='participating_actions', to='core.organizationalunit')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cause', models.TextField()),
                ('probability', models.PositiveSmallIntegerField()),
                ('impact', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('IDENTIFICADO', 'Identificado'), ('EM_TRATAMENTO', 'Em tratamento'), ('MATERIALIZADO', 'Materializado'), ('ENCERRADO', 'Encerrado')], default='IDENTIFICADO', max_length=16)),
                ('treatment', models.CharField(blank=True, max_length=20)),
                ('preventive_measure', models.TextField(blank=True)),
                ('contingency_measure', models.TextField(blank=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='core.activity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.strategicaction')),
            ],
        ),
        migrations.AddField(
            model_name='actionplan',
            name='action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan', to='core.strategicaction'),
        ),
    ]
