# Generated by Django 6.0.7 on 2026-09-05 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategicaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategicaction',
            name='funding_sources',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CriticalSuccessFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_success_factors', to='core.strategicaction')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('formula', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=80)),
                ('data_source', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(choices=[('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('QUADRIMESTRAL', 'Quadrimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('BIENAL', 'Bienal'), ('OUTRA', 'Outra')], default='ANUAL', max_length=16)),
                ('direction', models.CharField(choices=[('MAIOR_MELHOR', 'Maior é melhor'), ('MENOR_MELHOR', 'Menor é melhor'), ('FAIXA', 'Faixa esperada')], default='MAIOR_MELHOR', max_length=16)),
                ('baseline', models.CharField(blank=True, max_length=120)),
                ('artifacts', models.ManyToManyField(blank=True, related_name='indicators', to='core.planartifact')),
                ('responsible_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='core.organizationalunit')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_period', models.CharField(max_length=120)),
                ('measured_value', models.CharField(max_length=120)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.indicator')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategicTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField()),
                ('target_value', models.CharField(blank=True, max_length=120)),
                ('unit_of_measure', models.CharField(blank=True, max_length=80)),
                ('reference_period', models.CharField(blank=True, max_length=120)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='core.strategicaction')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='core.planartifact')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='indicators', to='core.strategictarget'),
        ),
    ]
