"""Quadro de Indicadores e Metas do PEI 2025-2034 (Apêndice A, págs. 40-45 do PDF).

Cada linha: (número, indicador, tipo, periodicidade, polaridade, finalidade, fórmula, meta, valor da meta).
O número "NN.N" liga as três pontas: IE NN.N → Mt NN.N → OE NN.
"""

E, R = "ESFORCO", "RESULTADO"
POS, NEG = "Positiva", "Negativa"

INDICATOR_ROWS = [
    ("01.1", "Percentual de servidores capacitados anualmente", E, "Anual", POS,
     "Aferir o percentual de servidores capacitados",
     "(Nº de servidores capacitados /nº total de servidores) x 100",
     "Capacitar 100% dos servidores até 2034.", "100%"),
    ("01.2", "Nível de satisfação dos servidores sobre as capacitações oferecidas", R, "Anual", POS,
     "Aferir nível de aprendizado dos servidores nos cursos realizados.",
     "(Nº de servidores satisfeitos/nº de servidores que participaram das capacitações) x 100",
     "Atingir 70% de satisfação dos servidores a cada ciclo de capacitação.", "70%"),
    ("02.1", "Taxa de crescimento do quadro de servidores", E, "Bienal", POS,
     "Aferir a taxa de crescimento do quadro dos servidores",
     "(Nº de servidores contratados /nº total de servidores) x 100",
     "Crescer o quadro de servidores em 10% até 2034.", "10%"),
    ("02.2", "Tempo médio de execução dos processos", R, "Anual, a contar de 2026", NEG,
     "Aferir o tempo médio gasto na execução dos processos em cada setor",
     "(somatório do Tempo de execução de cada processo /número total de processos executados)",
     "Reduzir em 10% o tempo médio do processo nos setores.", "10%"),
    ("03.1", "Índice de implementação do Programa de QVST", E, "Anual, a contar de 2026", POS,
     "Aferir o percentual de implementação do programa QVST",
     "(Etapas do programa implementadas / número total de etapas do programa)",
     "Implantar Programa de Qualidade de Vida e Saúde até 2034.", ""),
    ("03.2", "Total de atividades (palestras, workshops e campanhas de saúde, dentre outras) de QVST realizadas.", R, "Anual, a contar de 2026.", POS,
     "Aferir a quantidade de atividades de QVST realizadas ao ano",
     "Nº de atividades voltadas para a qualidade de vida e saúde no trabalho realizadas",
     "Realizar 03 (três) iniciativas de QVST anualmente.", "3 iniciativas"),
    ("03.3", "Percentual de satisfação dos servidores participantes das ações de QVST.", R, "Anual, a contar de 2026.", POS,
     "Aferir o percentual de satisfação dos servidores em relação às ações de QVST",
     "(Nº de servidores satisfeitos/nº de servidores que participaram das ações)x100",
     "Alcançar nível de satisfação acima de 70% dentre os participantes.", "70%"),
    ("03.4", "Percentual de participação dos servidores.", E, "Anual, a contar de 2026.", POS,
     "Aferir o percentual de participação dos servidores nas atividades de QVTS realizadas anualmente",
     "(Nº de servidores que participaram de pelo menos 1 atividade de QVTS no ano/nº total de servidores da sesed) x 100",
     "Alcançar participação de 70% dos servidores nas atividades realizadas anualmente.", "70%"),
    ("04.1", "Percentual de construção da Sede.", E, "Anual", POS,
     "Medir o avanço da construção da sede",
     "(área construída entregue/ área total da sede)x100",
     "Construir uma sede própria para a SESED até 2034.", ""),
    ("05.1", "Taxa de expansão da cobertura de radiocomunicação digital no RN", E, "Bienal, a contar de 2026.", POS,
     "Aferir a expansão da cobertura de radiocomunicação digital no RN",
     "(área da cobertura/ área total)x100",
     "Expandir o sistema de radiocomunicação digital troncalizado para 50% do território do RN.", "50%"),
    ("05.2", "Índice de implementação do DataCenter.", E, "Bienal, a contar de 2026.", POS,
     "Aferir a implementação do DataCenter",
     "(Nº de etapas implementadas / número total de etapas do DataCenter)x100",
     "Implantar o DataCenter de Backup da SESED.", ""),
    ("05.3", "Percentual de ações realizadas.", E, "Anual, a contar de 2026", POS,
     "Aferir a quantidade de ações de modernização em Tecnologia da Informação e Comunicação realizadas anualmente",
     "(Número de ações de modernização em Tecnologia da Informação e Comunicação realizadas/10) x 100",
     "Realizar 10 (dez) ações de modernização em Tecnologia da Informação e Comunicação", "10 ações"),
    ("05.4", "Percentual de integração dos sistemas entre as forças de segurança.", E, "Anual.", POS,
     "Aferir a taxa de integração dos sistemas da Secretaria com as demais forças de segurança",
     "(nº de sistemas integrados / nº total de sistemas)x100",
     "Integrar 100% dos sistemas da Secretaria com as outras forças de segurança até 2034.", "100%"),
    ("06.1", "Percentual de execução de recursos orçamentários da SESED.", E, "Anual", POS,
     "Aferir a execução dos recursos orçamentários da SESED",
     "[(Execução orçamentária do ano atual menos a do execução do ano anterior)/Execução do ano anterior] x 100",
     "Aumentar a eficácia da execução orçamentária em 5% anualmente.", "5%"),
    ("06.2", "Percentual de execução de recursos orçamentários do FaF.", E, "Anual", POS,
     "Aferir a execução dos recursos orçamentários do FaF",
     "[(Execução dos Recursos FaF do ano atual – Execução dos Recursos FaF do ano anterior)/Execução dos Recursos FaF do ano anterior] x 100",
     "Aumentar a execução orçamentária dos recursos FaF em 10% até 2034.", "10%"),
    ("07.1", "Índice de captação de recursos externos.", E, "Anual", POS,
     "Aferir o índice de captação de recursos externos.",
     "[(Recursos externos captados no ano atual – Recursos externos captados no ano anterior)/Recursos externos captados do ano anterior] x 100",
     "Aumentar em 10% a captação de recursos externos.", "10%"),
    ("07.2", "Percentual de ações para captação de recursos.", E, "Anual", POS,
     "Aferir o percentual de ações para captação de recursos.",
     "(Número de ações realizadas/ número total de ações propostas)",
     "Realizar 40 (quarenta) ações para captação de recursos até 2034.", "40 ações"),
    ("07.3", "Percentual de avanço da Implementação da assessoria parlamentar da SESED.", E, "Anual.", POS,
     "Medir o avanço da Implementação da assessoria parlamentar da SESED",
     "(número de etapas implementadas da assessoria parlamentar / Etapas propostas)x100",
     "Implementar a assessoria parlamentar da SESED para captação de recursos.", ""),
    ("08.1", "Percentual de órgãos do SISPRN com setores estruturados de governança.", E, "Anual, a partir de 2026", POS,
     "Aferir o percentual de órgãos do SISPRN com setores estruturados de governança",
     "(Número de órgãos do SISPRN estruturados /número total de órgãos do SISPRN) x 100",
     "Estruturar 100% dos órgãos do SISPRN com setores de governança até 2034.", "100%"),
    ("08.2", "Índice de adesão às boas práticas de governança estabelecidas", R, "Anual, a contar de 2026", POS,
     "Aferir a taxa de adesões às boas práticas de governança estabelecidas",
     "(Nº de órgãos em conformidade/Nº total de órgãos do SISPRN) x 100",
     "Adesão de 100% dos órgãos do SISPRN ao modelo de Gestão por Resultados.", "100%"),
    ("09.1", "Percentual de implantação do laboratório de inovação", E, "Anual, a contar de 2026", POS,
     "Aferir o percentual de implantação do laboratório de inovação",
     "(Número de estudos e projetos implementados / número de instrumentos necessários para a completa implementação do laboratório) x 100",
     "Implementar laboratórios de inovação até 2034.", ""),
    ("09.2", "Índice de soluções inovadoras implementadas", E, "Anual", POS,
     "Aferir o percentual de soluções inovadoras implementadas",
     "(Número de soluções inovadoras implementadas – número de soluções inovadoras propostas)x100",
     "Implementar 15 (quinze) soluções inovadoras até 2034.", "15 soluções"),
    ("10.1", "Percentual de processos padronizados na SESED", E, "Anual", POS,
     "Aferir o percentual de processos padronizados na SESED",
     "(Número de processos padronizados / número total de processo da SESED) x 100",
     "Padronizar 100 (cem) processos até 2034.", "100 processos"),
    ("10.2", "Percentual de criação de cartilhas, guias ou manuais", E, "Anual", POS,
     "Aferir o percentual de criação de cartilhas, guias ou manuais",
     "(Número de cartilhas, guias ou manuais criados / número de cartilhas, guias ou manuais propostos)x100",
     "Elaborar 10 (dez) cartilhas, guias ou manuais de procedimento operacional-padrão até 2034.", "10 documentos"),
    ("10.3", "Índice de redução do tempo médio de execução dos processos", R, "Anual, a contar de 2026", NEG,
     "Aferir o índice de redução do tempo médio de execução dos processos",
     "[(Tempo médio de execução do processo antigo - Tempo médio de execução do processo atual) / Tempo médio de execução do processo antigo] x 100.",
     "Reduzir em 10% o tempo médio de execução dos processos.", "10%"),
    ("11.1", "Índice de parcerias efetivadas", E, "Bienal", POS,
     "Aferir o índice de parcerias efetivas",
     "(número de parcerias consolidadas) / parcerias previstas) x 100",
     "Efetivar 05 (cinco) novas parcerias até 2034.", "5 parcerias"),
    ("11.2", "Índice de projetos colaborativos efetivados", E, "Bienal", POS,
     "Aferir o índice de projetos colaborativos efetivados",
     "(número de projetos implementados / projetos propostos) x 100",
     "Efetivar 05 (cinco) projetos colaborativos até 2034.", "5 projetos"),
    ("12.1", "Percentual de operações especiais articuladas pela SESED", E, "Anual", POS,
     "Aferir o percentual de operações especiais articuladas pela SESED",
     "(número de operações especiais integradas /número de operações especiais previstas) x 100",
     "Articular 10 (dez) operações especiais integradas até 2034.", "10 operações"),
    ("12.2", "Taxa de índices de homicídios", R, "Anual", NEG,
     "Aferir a taxa de índices de homicídios",
     "(número de homicídios/ população)*100mil",
     "Reduzir índices de homicídios para 20 (vinte) por 100 (cem) mil habitantes até 2034.", "20 por 100 mil"),
    ("12.3", "Taxa de mortes violentas de mulheres", R, "Anual", NEG,
     "Aferir a taxa de mortes violentas de mulheres",
     "(número de mortes violentas de mulheres/população do sexo feminino)*100mil",
     "Reduzir a taxa de mortes violentas de mulheres para abaixo de 03 (três) até 2034", "Abaixo de 3"),
    ("12.4", "Quantidade de drogas apreendidas.", R, "Anual", POS,
     "Aferir o percentual de aumento anual do número de ações contra o tráfico de drogas.",
     "Número absoluto (em Kg/Ton) de drogas apreendidas",
     "Aumentar em 10% a quantidade de drogas apreendidas, em kg.", "10%"),
    ("12.5", "Índice de ocorrências registradas pelo CIOSP.", R, "Anual", NEG,
     "Aferir o índice de ocorrências registradas pelo CIOSP.",
     "(número de ocorrências registradas no ano anterior – o número de ocorrências registradas no ano atual) x 100",
     "Reduzir o número de ocorrências de poluição sonora e perturbação do sossego alheio em 50% até 2034.", "50%"),
    ("13.1", "Percentual de criação e implementação do programa Policial Educador", E, "Anual", POS,
     "Aferir o percentual de criação e implementação do programa Policial Educador",
     "(número de etapas implementadas / número de etapas previstas no programa policial educador) x 100",
     "Criar e implementar o Programa Policial Educador.", ""),
    ("13.2", "Índice de ações de fomento à cidadania e participação social.", E, "Anual", POS,
     "Aferir o índice de ações de fomento à cidadania e participação social",
     "(número de ações de fomento à cidadania e participação social realizadas /número de ações de fomento à cidadania e participação social previstas) x 100",
     "Realizar 10 (dez) ações de fomento à cidadania e participação social até 2034.", "10 ações"),
    ("13.3", "Índice de engajamento dos participantes nas ações de fomento à cidadania.", R, "Anual", POS,
     "Aferir o índice de engajamento dos participantes nas ações de fomento à cidadania",
     "(Número de participantes engajados/número de participantes totais nas ações) x 100",
     "Atingir o engajamento de 70% dos participantes nas ações de fomento à cidadania.", "70%"),
    ("13.4", "Percentual de formação e implementação dos CCDS'S", E, "Anual", POS,
     "Aferir o percentual de formação e implementação dos CCDS'S",
     "(Número de Conselhos Comunitários de Defesa Social implementados / número de Conselhos Comunitários de Defesa Social totais previstos)",
     "Expandir a 100% dos municípios do RN a criação dos CCDSs", "100%"),
    ("13.5", "Percentual de publicação da revista “CIDADANIA & SEGURANÇA PÚBLICA”", E, "Anual", POS,
     "Aferir o percentual de publicação da revista “CIDADANIA & SEGURANÇA PÚBLICA”",
     "(Número de publicações da revista “CIDADANIA & SEGURANÇA PÚBLICA” realizadas / número de publicações da revista “CIDADANIA & SEGURANÇA PÚBLICA” previstas) x 100",
     "Publicar 10 (dez) edições da revista “CIDADANIA & SEGURANÇA PÚBLICA” até 2034.", "10 edições"),
]
